MDW-3793: Data mon. Ability to open DICOM in the viewer from S3
MDWio/OpenSearch-Dashboards pull request #1
Opened 2023-04-05 15:50 UTC by alexandrborisovyg

Подробности в 3793

WIP:
дорабатывается интерфейс, функциональность готова

2023-04-27 08:00 UTC, jimOnAir requested changes

2023-04-27 08:00 UTC, jimOnAir commented on src/dev/build/tasks/os_packages/docker_generator/run.ts
> +  const imageTag = 'opensearchproject/opensearch-dashboards';
```ts
const imageTag = 'nanoxmarketplace/opensearch-dashboards';
```

2023-04-27 08:00 UTC, jimOnAir commented on src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile
> -RUN find /usr/share/opensearch-dashboards -type d -exec chmod g+s {} \;
зачем удалил?

2023-04-28 00:46 UTC, justvamp commented
test

2023-04-28 00:49 UTC, justvamp commented
test2

2023-04-28 00:51 UTC, justvamp commented
test 3

2023-04-28 06:38 UTC, alexandrborisovyg commented on src/dev/build/tasks/os_packages/docker_generator/run.ts
> +  const imageTag = 'opensearchproject/opensearch-dashboards';
fixed

2023-04-28 06:38 UTC, alexandrborisovyg commented on src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile
> -RUN find /usr/share/opensearch-dashboards -type d -exec chmod g+s {} \;
удалил эту строчку в рамках фикса по ошибке при стягивании centos имиджа, по этому гайду делал, использую сейчас образ almalinux
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1601#issuecomment-1135335603

2023-05-03 04:12 UTC, merged