MDW-4514: Opensearch. Allow the end user to write study notes
MDWio/OpenSearch-Dashboards pull request #10
Opened 2024-02-29 16:33 UTC by alexandrborisovyg

4514
4517

2024-03-01 03:51 UTC, alekschernof approved these changes

2024-03-01 03:51 UTC, alekschernof commented on src/plugins/discover/public/application/angular/doc_table/components/study_notes_modal/study_notes_modal.tsx
> +        reject(
не хотим ли мы такое выносить или оброрачичать в useCallback ?

2024-03-01 13:29 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/study_notes_modal/study_notes_modal.tsx
> +        reject(
не уверен, что конкретно в этой ситуации нужны useCallback

2024-03-04 05:04 UTC, jimOnAir requested changes

2024-03-04 05:04 UTC, jimOnAir commented on src/plugins/discover/public/application/angular/doc_table/components/study_notes_modal/study_notes_modal.tsx
> +        field: 'Comments',
в истории поле называется `studynotes`

2024-03-04 05:04 UTC, jimOnAir commented on src/plugins/discover/server/ui_settings.ts
> +  },
у нас же фикстированные API, зачем нам указывать url для каждого эндпоинта?

2024-03-04 08:18 UTC, alekschernof approved these changes

2024-03-04 13:34 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/study_notes_modal/study_notes_modal.tsx
> +        field: 'Comments',
уточнил, должно быть Comments везде, переименовал во всех местах

2024-03-04 13:34 UTC, alexandrborisovyg commented on src/plugins/discover/server/ui_settings.ts
> +  },
создал отдельный файл api.ts, хранящий в себе все эндпоинты

2024-03-05 08:22 UTC, jimOnAir approved these changes

2024-03-05 10:27 UTC, justvamp commented
need merge dev

2024-03-12 12:56 UTC, andreidubov approved these changes

2024-03-12 12:56 UTC, andreidubov commented on src/plugins/discover/public/application/angular/doc_table/components/table_row/cell-actions.html
> +                    <path fill-rule="evenodd" clip-rule="evenodd" d="m3.99 16.854-1.314 3.504a.75.75 0 0 0 .966.965l3.503-1.314a3 3 0 0 0 1.068-.687L18.36 9.175s-.354-1.061-1.414-2.122c-1.06-1.06-2.1
euiIcon-isLoaded - зачем тут такой стиль? из-за этого свойства при рендеренге иконка мигает, думаю лучше убрать на всех кнопках.

2024-03-12 18:43 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/table_row/cell-actions.html
> +                    <path fill-rule="evenodd" clip-rule="evenodd" d="m3.99 16.854-1.314 3.504a.75.75 0 0 0 .966.965l3.503-1.314a3 3 0 0 0 1.068-.687L18.36 9.175s-.354-1.061-1.414-2.122c-1.06-1.06-2.1
у других компонентов в OpenSearch он использовался, я просто перенес, если он создает проблему при обновление, то да, можно убрать, убрал

2024-03-13 07:12 UTC, andreidubov approved these changes

2024-03-14 06:44 UTC, alekschernof approved these changes

2024-03-20 10:35 UTC, merged