MDW-4516: Opensearch. View two studies side by side
MDWio/OpenSearch-Dashboards pull request #11
Opened 2024-03-12 06:42 UTC by andreidubov

https://mdwebio.atlassian.net/browse/MDW-4516

2024-03-12 11:40 UTC, alekschernof approved these changes

2024-03-12 11:40 UTC, alekschernof commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/viewer_open_modal.tsx
> +    const parsedSource = [] as IDicomJson[];
а почему не сделать сразу `new Array<IDicomJson>()`

2024-03-12 11:40 UTC, alekschernof commented on src/plugins/discover/public/application/components/discover_legacy.tsx
> +    setShowBar(selectedRows?.length > 0);
some в одну строку можно сделать

2024-03-12 11:48 UTC, andreidubov commented on src/plugins/discover/public/application/components/discover_legacy.tsx
> +    setShowBar(selectedRows?.length > 0);
Можно, только там дальше еще 2 строчки где length нужен, поэтому раз все равно нужен length, думаю можно оставить filter
![image](https://github.com/MDWio/OpenSearch-Dashboards/assets/58589743/f867d959-1d2e-4536-9de3-c6dadb247f3e)

2024-03-12 11:49 UTC, alekschernof commented on src/plugins/discover/public/application/components/discover_legacy.tsx
> +    setShowBar(selectedRows?.length > 0);
а точно

2024-03-12 13:09 UTC, andreidubov commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/viewer_open_modal.tsx
> +    const parsedSource = [] as IDicomJson[];
поправил

2024-03-12 13:17 UTC, alekschernof commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/viewer_open_modal.tsx
> +    const parsedSource = [] as IDicomJson[];
в выше может тоже

2024-03-13 07:16 UTC, andreidubov commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/viewer_open_modal.tsx
> +    const parsedSource = [] as IDicomJson[];
Да, точно, упустил, спасибо. Поправил

2024-03-14 06:32 UTC, alekschernof approved these changes

2024-03-14 14:31 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/table_header/table_header_column.tsx
> +        {/* {buttons
todo можно добавить, почему закомментировано

2024-03-14 14:36 UTC, alexandrborisovyg approved these changes

2024-03-18 14:10 UTC, alexandrborisovyg requested changes

2024-03-18 14:10 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/archiver_modal/archiver_open_modal.tsx
> +  isExportFromHitsCounter?: boolean;
в useEffect нужно добавить, иначе скачивается только первая стадия
```ts
useEffect(() => {
    if (!props.isExportFromHitsCounter) {
      setFilesAmount(props.rows.length);
    }
    if (requestUid) {
      getArchiveStatus();
    }
  }, [loopMutex]);
```

2024-03-19 05:57 UTC, andreidubov commented on src/plugins/discover/public/application/angular/doc_table/components/archiver_modal/archiver_open_modal.tsx
> +  isExportFromHitsCounter?: boolean;
Точно, спасибо, упустил

2024-03-19 05:58 UTC, andreidubov commented on src/plugins/discover/public/application/angular/doc_table/components/table_header/table_header_column.tsx
> +        {/* {buttons
Добавил TODO

2024-03-19 09:52 UTC, justvamp approved these changes

2024-03-19 09:52 UTC, justvamp commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/viewer_open_modal.tsx
> +    <></>
пустые теги?

2024-03-19 09:52 UTC, justvamp commented on src/plugins/discover/public/application/angular/doc_table/components/table_row/_cell.scss
> +  transform: scale(1.3);
нужны ли вендор-префиксы?

2024-03-19 10:07 UTC, alekschernof commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/viewer_open_modal.tsx
> +    <></>
мир реакта
это фрагменты типо что бы в лишний div не оборачивать или писать React.fragment

2024-03-19 12:50 UTC, andreidubov commented on src/plugins/discover/public/application/angular/doc_table/components/table_row/_cell.scss
> +  transform: scale(1.3);
не нужны, убрал, с просто transform работает

2024-03-19 13:08 UTC, justvamp approved these changes

2024-03-26 07:40 UTC, alexandrborisovyg approved these changes

2024-03-26 07:43 UTC, merged