MDW-4571: OpenSearch. Arc Studies. Auditing
MDWio/OpenSearch-Dashboards pull request #12
Opened 2024-03-26 13:41 UTC by alexandrborisovyg

Подробности в тиките

2024-03-26 14:45 UTC, alekschernof approved these changes

2024-03-26 14:45 UTC, alekschernof commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/utils.ts
> +  const fileNamesArray = Array.isArray(fileNames) ? fileNames : [fileNames];
fileNames может быть не массив ?
там выше тип

2024-03-27 11:12 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/utils.ts
> +  const fileNamesArray = Array.isArray(fileNames) ? fileNames : [fileNames];
сам opensearch может вернуть как массив, когда несколько имен, так и строку, когда один файл, поэтому это воркэраунд для ситуации, когда приходит одно имя как строка, а не массив

2024-03-28 07:37 UTC, alekschernof commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/utils.ts
> +  const fileNamesArray = Array.isArray(fileNames) ? fileNames : [fileNames];
тогда может тип выше расширить 
и коментарий можно

2024-03-28 08:03 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/utils.ts
> +  const fileNamesArray = Array.isArray(fileNames) ? fileNames : [fileNames];
fixed

2024-04-01 21:12 UTC, alekschernof approved these changes

2024-04-02 08:47 UTC, justvamp commented on src/plugins/discover/server/ui_settings.ts
> +    value: 'archive.marketplace.nanox.vision',
значения для dev и prod теперь одинаковые?

2024-04-02 08:52 UTC, jimOnAir requested changes

2024-04-02 08:52 UTC, jimOnAir commented on src/plugins/discover/public/application/angular/doc_table/components/archiver_modal/archiver_open_modal.tsx
> +    const index = props.rows[0]?._index;
где-то есть проверка на количество строк (что есть нулевая строка)?

2024-04-02 08:52 UTC, jimOnAir commented on src/plugins/discover/public/application/components/discover_legacy.tsx
> +                                  const index = filteredRows[0]?._index;
не нужно ли проверить наличие 0-го элемента?

2024-04-02 08:52 UTC, jimOnAir commented on src/plugins/discover/public/application/components/discover_legacy.tsx
> +                                  const index = filteredRows[0]?._index;
и тут

2024-04-02 12:53 UTC, alexandrborisovyg commented on src/plugins/discover/server/ui_settings.ts
> +    value: 'archive.marketplace.nanox.vision',
это дефолтные значения, которые нужны только для разработки, локально они используют один и тот же бакет, поэтому и обновил

для прода и дева значения сейчас стоят разные

2024-04-02 12:53 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/archiver_modal/archiver_open_modal.tsx
> +    const index = props.rows[0]?._index;
fixed

2024-04-02 12:53 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/components/discover_legacy.tsx
> +                                  const index = filteredRows[0]?._index;
fixed

2024-04-02 12:53 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/components/discover_legacy.tsx
> +                                  const index = filteredRows[0]?._index;
fixed

2024-04-02 13:56 UTC, jimOnAir approved these changes

2024-04-03 07:40 UTC, justvamp approved these changes

2024-04-03 07:42 UTC, merged