MDW-3904: Data mon. Opensearch. Generating a link to download filtered studies
MDWio/OpenSearch-Dashboards pull request #2
Opened 2023-05-10 07:37 UTC by alexandrborisovyg

Подробности в 3904

2023-05-12 10:58 UTC, jimOnAir requested changes

2023-05-12 10:58 UTC, jimOnAir commented on src/plugins/discover/public/application/angular/doc_table/components/archiver_modal/archiver_open_modal.tsx
> +        console.log(res);
мусор?

2023-05-12 10:58 UTC, jimOnAir commented on src/plugins/discover/public/application/angular/doc_table/components/archiver_modal/archiver_open_modal.tsx
> +      const body = composeBodyFromRows(replacedS3Domain);
Думаешь не нужно на платформе сравнить тот ли бакет используется?

2023-05-12 10:58 UTC, jimOnAir commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/viewer_open_modal.tsx
> +  const s3path = props.source.dicom_filepath.replace(`s3://archive.nanox.vision/`, '');
что за хардкод? Другой бакет уже нельзя использовать?

2023-05-12 10:58 UTC, jimOnAir commented on src/plugins/discover/public/application/components/hits_counter/hits_counter.tsx
> +  rows: any;
не нужно им какой-то минимальный интерфейс добавить?

2023-05-12 10:58 UTC, jimOnAir commented on src/plugins/discover/public/application/components/hits_counter/hits_counter.tsx
> +  rows: any;
можно прямо в quicktype.io  сгенерировать из json

2023-05-12 13:31 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/archiver_modal/archiver_open_modal.tsx
> +        console.log(res);
fixed, убрал console.log

2023-05-12 13:31 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/archiver_modal/archiver_open_modal.tsx
> +      const body = composeBodyFromRows(replacedS3Domain);
в принципе можно, в данном случае я убираю из путей этот домен, чтобы дальше не убирать его для каждого файла на платформе

но проверку добавил по значению REMOVE_AMAZON_ENDPOINT, на платформе код также обновил

2023-05-12 13:32 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/angular/doc_table/components/viewer_modal/viewer_open_modal.tsx
> +  const s3path = props.source.dicom_filepath.replace(`s3://archive.nanox.vision/`, '');
fixed, локальный код просочился, конечно здесь как и везде должно браться из uiSettings

2023-05-12 13:32 UTC, alexandrborisovyg commented on src/plugins/discover/public/application/components/hits_counter/hits_counter.tsx
> +  rows: any;
добавил, сгенерировал с помощью qiucktype.io

2023-05-15 11:11 UTC, jimOnAir approved these changes

2023-05-16 02:03 UTC, justvamp approved these changes

2023-05-31 11:36 UTC, merged